### ISSUE TITLE
For vue-apollo@3 and apollo-client@3, an old apollo-client@2 is still required.

### ISSUE THREAD

**Issue by TQ-Benji** [Akryum/vue-apollo#1211]
Describe the bug
After upgrading from apollo-v2 to apollo-v3 and vue-apollo from v2.* to v3.* vue-apollo still requires old dependencies from the apollo-client package.

Old closed issue that wasn't fully fixed - https://github.com/vuejs/vue-apollo/issues/1059
Related discussion https://github.com/vuejs/vue-apollo/discussions/1079

To Reproduce

Upgrade project following an official tutorial: https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#updating-imports
Delete unneeded apollo-client library.
Run project.
Get err..
node_modules/vue-apollo/types/vue-apollo.d.ts
13:28 Cannot find module 'apollo-client/util/Observable' or its corresponding type declarations.
    11 | } from 'apollo-client'
    12 | import { FetchResult } from 'apollo-link'
  > 13 | import { Observable } from 'apollo-client/util/Observable'
       |                            ^
    14 | import { ApolloProvider, VueApolloComponent } from './apollo-provider'
    15 | import {
    16 |   VueApolloQueryDefinition,
    
Expected behavior
Replace imports an old dependencies from apollo-client with new imports from@apollo/client.

Versions

  "vue-apollo": "^3.0.7",
  "@apollo/client": "^3.3.20",
  "vue": "^2.6.14",

**Comment by HansCronau** [comment]
Another example is in [`apollo-provider.d.ts`](https://github.com/vuejs/vue-apollo/blob/dev/packages/vue-apollo/types/apollo-provider.d.ts):
```
import { ApolloClient } from 'apollo-client'
```
I had to manually change that to `@apollo/client` in order not to get the following error when giving `VueApollo` a `defaultClient` created with the `ApolloClient` from `@apollo/client`:
```
Type 'ApolloClient<NormalizedCacheObject>' is missing the following properties from type 'ApolloClient<any>': store, writeData, initQueryManager
```

**Comment by HansCronau** [comment]
@EM-Benji Note that all Vue Apollo [documentation] still instructs to install `apollo-client` 2 as a peer dependency instead of `@apollo/client` 3.
Confusingly it seems this will change only starting [Vue Apollo 4].

[documentation]: https://apollo.vuejs.org/guide/installation.html
[Vue Apollo 4]: https://v4.apollo.vuejs.org/guide/installation.html

**Comment by TQ-Benji** [comment]
@HansCronau I know the docs say install apollo-client but then why does the package depend on @apollo/client as shown in the package.json https://github.com/vuejs/vue-apollo/blob/92a4a11e2627d39981f2c9ec1e46e1fc9e6dcb09/packages/vue-apollo/package.json#L47 and the commit https://github.com/vuejs/vue-apollo/issues/1059#issuecomment-709331356 that adds it so you end up needing both apollo-client and @apollo/client.

either be fully updated to use only @apollo/client and update docs for v3 or revert the dependency changes on v3 and make @apollo/client a v4 only change.

**Comment by HansCronau** [comment]
@EM-Benji The line you are pointing to is a dev dependency of `vue-apollo` 3. It is not a peer dependency and AFAIK you are not required to install it alongside `apollo-client` 2.
I believe issue #1059 was closed, because @mstys incorrectly assumed that `vue-apollo` 3 was supposed to support `@apollo/client` 3. In his defense: I made the same mistake and it took me a day to realise why stuff didn't work as I had expected.

That does leave your question: why does `vue-apollo` 3.0.7 have a (dev) dependency on `@apollo/client` 3? I'm not entirely sure. Going by the message of commit 6dc7c8e, which introduced the change, it appears the goal was to fix TypeScript typing.

The help the Vue Apollo devs manage issues: could I suggest closing this issue, or updating the title?
