### ISSUE TITLE
@vue/apollo-option fails during ssr

### ISSUE THREAD

**Issue by Csszabi98** [Akryum/vue-apollo#1424]
**Describe the bug**
When @vue/apollo-option mixin is being called on the server the patching of the render function fails as
the code of the library refers to the vue render function incorrectly. During ssr the render function of a vue 
component is called ["ssrRender" rather than "render"](https://github.com/vitejs/vite/blob/main/packages/plugin-vue/src/main.ts#L289).

[Problematic code piece](https://github.com/vuejs/apollo/blob/6c07a47d33e6a59643a3a4f743e8fa43e435abf4/packages/vue-apollo-option/src/mixin.js#L117)

**To Reproduce**
1. Run any app with @vue/apollo-option with a production build (vite preview)
2. Open a page which uses apollo during ssr.

**Expected behavior**
The patching of the cleanup function should not fail.

**Versions**
vue: 3.2.37
vue-apollo: 4.0.0-alpha.20
@apollo/client: 3.6.9

**Comment by seuck** [comment]
Thanks for providing a solution. Would be great to have it fixed soon.

**Comment by icyJochen** [comment]
I got the same issue in my project and looking forward to a fix soon.
Thanks for providing this fix

**Comment by MartDD** [comment]
We had similar issues, looking forward to the fix.

**Comment by taksugit** [comment]
As you said, after upgrading to Nuxt 3.1.0 (Vite4), I encountered the error in production build

Nevertheless, it seems that direct rewriting to `ssrRender` would be not good because it affects users other than Vite.

Therefore, regarding the patch about clearing Apollo to prevent memory leaks, I suppose we should use another permanent approach.
