### ISSUE TITLE
Store cache issue

### ISSUE THREAD

**Issue by Nainterceptor** [Akryum/vue-apollo#146]
Hello,

I'm using Nuxt with apollo-module.

I have an issue, when I have routes with child, I've a cache fail on parent routes. You can see the issue here : https://github.com/Nainterceptor/nuxt.js/tree/issue/store-cache/examples/vue-apollo (or live in https://nuxt-vue-apollo-elszaxsupq.now.sh).

I'm on the homepage, I click on a car, I refresh, then I click on another car, the main list disappear.

I'm trying to find the issue without success

Reported here https://github.com/Akryum/vue-apollo/issues/127 but seems to be in dependency.

Thanks !

**Comment by Evild67** [comment]
Same problem for me. Some times when i go back, cache is not loaded :/

**Comment by Nasirkhan-rpl** [comment]
@Nainterceptor what you are trying to do is get list on each page, right? if yes, then cache is not a good way to achieve this since you can do this in a much easy way using nuxt. All you have to do is place your list  inside layouts componet. you can inspect this [repo](https://github.com/Lahori-Jawan/graphX)

**Comment by Akryum** [comment]
Please reopen if you still have the issue.
