### ISSUE TITLE
Option for client in smart queries

### ISSUE THREAD

**Issue by CunningFatalist** [Akryum/vue-apollo#352]
Hello,

it seems like it is not possible to define a [different client](https://akryum.github.io/vue-apollo/guide/multiple-clients.html) than the default one when using 

```
created () {
  this.$apollo.addSmartQuery('comments', {
    // Same options like above
  })
}
```

Was this restriction added on purpose? Is there another way to do it? I thought about using `this.$apollo.client = 'myOtherclient'`, but the `d.ts` file makes me think this is not something I'm supposed to do (and probably for good reason). If this option was _not_ omitted on purpose, are there any plans to add this in a future update?

Thanks a lot and keep up the good work 😃 

Cheers

**Comment by fnoop** [comment]
I think you can do this, no?
```
created () {
  this.$apollo.addSmartQuery('comments', {
    client: "clientname",
    query: gql`blah`
  })
}
```

**Comment by CunningFatalist** [comment]
Accordiong to `types/options.d.ts`, no you cannot. As far as I remember, we also tried this and it did not work. To be fair, though, by now we have implemented a workaround and I might misremember what I wrote back in August 😄

**Comment by fnoop** [comment]
Hi, I came across this issue yesterday because I was trying to do a similar thing, in my case create the same connection to three separate clients.  This is my code:
```
created () {
    for (var api in this.$store.state.apis) {
      this.$apollo.addSmartQuery('nav' + api, {
        client: api,
        query: navSatFixQuery
      })
      console.log('queries: ', this.$apollo.queries)
    }
  }
```
Then looking at each resulting SmartQuery.client it does look like the different clients are being correctly bound and the SmartQuery options show the different clients (note the options.client and also client.wsClient.url):
![screenshot 2018-11-15 at 08 32 39](https://user-images.githubusercontent.com/8210968/48540154-3d4b4a80-e8b1-11e8-8e1c-39e13740d366.png)

![screenshot 2018-11-15 at 08 32 52](https://user-images.githubusercontent.com/8210968/48540157-40463b00-e8b1-11e8-81dd-d9a42dfd6330.png)

**Comment by CunningFatalist** [comment]
Hey,

this is pretty cool. Maybe it was fixed in one of the releases (there were quite a few) since August or maybe I just misremember the actual problem. Anyway, this is great for people with the same issue coming here from search engines. I will close this issue as the problem seems to be solved, thanks for sharing your solution 👍
