### ISSUE TITLE
edge arrays 

### ISSUE THREAD

**Issue by hounded** [Akryum/vue-apollo#373]
This is what I have running on aws-appsync, works fine

```graphql
query getShit{
  getAllDevices{
    items{
      id
      device    
    }
  }
}
```
![awsql](https://user-images.githubusercontent.com/11545495/44843575-b963c800-ac9c-11e8-86f4-e18cf9a20faf.png)

On my application however I have the just the first result repeating 

![consoleql](https://user-images.githubusercontent.com/11545495/44843726-0fd10680-ac9d-11e8-9ff3-bbfd1e4ae450.png)

Was googling about and did see this;

https://stackoverflow.com/questions/48840223/apollo-duplicates-first-result-to-every-node-in-array-of-edges/49249163#49249163

 i'm pretty new to vue and graphql, is there a fix to this?

**Comment by paulpdaniels** [comment]
The answer right above it answers your question, the problem is that apollo looks for an `id` field on objects and uses those to cache the object (default is `<typename>:<id>`). If you want it to work in the general case then you can modify the `dataIdFromObject` to handle that particular type. Easier (and more readable) would be to simply change your document to:

```
query {
  getAllDevices {
    items {
      userId: id
      id: device
    }
  }
}
```

That will make it cache by the `device` instead of the `id` field

**Comment by hounded** [comment]
Thanks for that works like a treat!
