### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by Austio** [Akryum/vue-apollo#730]
VueApollo is really awesome, it helped us and our team integrate apollo into our spa and we have used it for almost 2.5 years at this point.

As of late, there has not been a lot of activity on this repo, there are many outstanding prs, some of which improve the system quite a bit.  I wanted to discuss bringing on additional maintainers, forking the repo or merging in to official vue repo in order to keep relevant fixes merged in and get more people active on the project.  In my view, it is the only way we can get vue-apollo up to the same level of contributors/community as with react-apollo.  

I very much appreciate the work that has went into this project.

**Comment by Austio** [comment]
@Akryum So what are you thinking.  How can we help, what do you think the best approach is?

**Comment by Akryum** [comment]
I need to think about this. You bring up good points, but people contributing to PRs already are very helpful. Maybe if some people can review them it would be awesome so that when I have time I can merge them and do a new release.

**Comment by Akryum** [comment]
Also issue triaging could be very helpful from other members of the community.

**Comment by ALITHEALI** [comment]
Hello!

I have used this project on multiple projects of mine with 0 problem! Thanks a lot for this amazing project but when I suggest my team to use it the company they bring up this issue about maintenance of the project and to be honest it is the only reason preventing us to use this project in the company since it is not in stable version.  Is there anything that can we help to get this project to V 1.0.0 stable? Once again thanks for all the effort that has gone through this project.

**Comment by Austio** [comment]
@Akryum any additional thoughts after thinking on it?
